### ISSUE TITLE
[FEATURE] 관리자 - 메뉴 관리 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by somine320** [Cafe-Manage-Service-CAFE-IN/cafe-in#1]
## 🌳 작업 브랜치

`feature/#1`

## 📝 TASK 개요
관리자 모드의 메뉴 관리와 관련된 마크업과 스타일 적용

## ✅ TO DO 및 진행현황
- [X] 메뉴 관리 페이지
- [X] 메뉴 관리 페이지 다크모드
- [X]  메뉴 추가 모달
- [X]  메뉴 추가 모달 다크모드
- [X]  메뉴 수정/삭제 모달
- [X]  메뉴 수정/삭제 모달 다크모드
- [X]  메뉴 삭제 확인 모달
- [X]  메뉴 삭제 확인 모달 다크모드
- [X]  카테고리 관리 모달
- [X]  카테고리 관리 모달 다크모드
