### ISSUE TITLE
[REFACTOR] 웹 접근성 및 성능 개선

### ISSUE THREAD

**Issue by somine320** [Cafe-Manage-Service-CAFE-IN/cafe-in#105]
## 🌳 작업 브랜치

`feature/#105`

## 🔨 REFACTORING 개요
Lighthouse 검사를 통해 접근성 및 성능 개선이 필요한 부분에 대한 리팩토링 

## ✅ TODO 및 진행현황
- [X] 관리자 로그인 페이지 접근성 및 성능 개선
- [X] 메뉴 관리 페이지 접근성 및 성능 개선
- [X] 주문 내역 관리 페이지 접근성 및 성능 개선

## 🚧 REFACTOR 리포트
저시력자를 위해 색사 대비율을 개선했으며, 스크린 리더를 고려하여 중복된 label 이 없도록 개선했다.
