### ISSUE TITLE
[REFACTOR] 다크 모드 적용 안된 부분 수정 및 불필요한 코드 수정

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#110]
## 🌳 작업 브랜치

`refactor/#110`

## 🔨 REFACTORING 개요

- 다크 모드 적용 안된 부분 수정
- 불필요한 코드 수정

## ✅ TODO 및 진행현황

- [x] 불필요한 코드 수정
- [x] 시작 페이지 
- [x] 포인트 조회 페이지
- [x] 관리자 메인 페이지
