### ISSUE TITLE
[REFACTOR] 배포전 수정 사항 

### ISSUE THREAD

**Issue by Anyudbwls** [Cafe-Manage-Service-CAFE-IN/cafe-in#118]
## 🌳 작업 브랜치

`feature/#91`

## 🔨 REFACTORING 개요
메뉴 리스트에서 메뉴 아이템 담고 홈 버튼 누르고 다시 메뉴 리스트 왔을때 전의 아이템 선택된 상태로 남아있음 

함수 사용 ! 

결제 눌렀을때 포인트 데이터 업데이트
메뉴 리스트 로고 눌렀을때 커피 선택 해제
카테고리 많아지면 슬라이드
로고 눌렀을 때 전체 메뉴 -> 정렬 추가하기

## ✅ TODO 및 진행현황

- [x] 홈 버튼 클릭시 selecetedItem 초기화 
- [x] 포인트 업데이트 결제하기 클릭
- [x] 카테고리  많아지면 슬라이드 처리 
- [x] 전체 메뉴 정렬 추가하기
