### ISSUE TITLE
[REFACTOR] 메뉴 관리, 주문 관리 스타일 수정  및 eslint 경고 코드 수정

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#128]
## 🌳 작업 브랜치

`refactor/#128`

## 🔨 REFACTORING 개요

메뉴 관리 스타일 수정

## ✅ TODO 및 진행현황

- [x] 선택 색상에 따라 체크 박스 색상 변경
- [x] 메뉴 관리 헤더 텍스트 수정
- [x] 메뉴 관리 이미지 border-radius 설정
- [x] eslint 경고 코드 수정
