### ISSUE TITLE
[REFACTOR] 대기 관리 페이지 리팩토링

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#134]
## 🌳 작업 브랜치

`refactor/#134`

## ✅ TODO 및 진행현황

- [ ] 비지니스 로직 분리
- [ ] 코드 가독성 높이기
- [ ] DB 커스텀 훅 적용
- [ ] useState 관리하는 커스텀 훅 적용
- [ ] 성능 향상
