### ISSUE TITLE
[FEATURE] 관리자 - 대기 관리

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#15]
## 🌳 작업 브랜치

`feature/#15`

## 📝 TASK 개요
대기 관리 페이지 대기 신청 정보 렌더링 및 기능 구현

### 대기 신청 정보 렌더링

- [x] 파이어베이스 DB 연동
- [x] 대기 팀 정보 렌더링
- [x] 현재 대기팀 수 | 전체 대기 팀 수 가져오기
- [x] 대기 중 | 대기 완료 구분에 따라 다르게 데이터 렌더링 하기
- [x] 대기 중 | 대기 완료 구분에 따라 테이블 메뉴 및 헤더 메뉴 변경

### 대기 관리 기능
- [x] 모달 띄우기 (착석 완료 | 알림 | 취소)
- [x] 모달 유형에 따라 다르게 렌더링하기
- [x] 착석 완료 클릭 시 status를 seated로 변경하여 DB 업데이트
- [x] 취소 클릭 시 status를 cancel로 변경하여 DB 업데이트
~~- [ ] 대기 가능 클릭 시 대기 신청 가능 | 대기 마감 시 대기 신청 불가능 -> 대기 신청 페이지랑 연동~~
-> 대기 신청 작업 때 진행
