### ISSUE TITLE
[FEATURE] 관리자 - 카테고리 관리

### ISSUE THREAD

**Issue by somine320** [Cafe-Manage-Service-CAFE-IN/cafe-in#17]
## 🌳 작업 브랜치
feature/#17

## 📝 TASK 개요
메뉴 관리 페이지 카테고리 관리 기능 추가

## ✅ TO DO 및 진행현황
- [X] 파이어베이스 연동 확인 
- [X] 카테고리 관리 버튼 클릭시 모달 띄우기 
- [X] 카테고리 추가
- [X] 카테고리 수정
- [X] 카테고리 삭제 
- [X] 취소 버튼 클릭시 별도의 처리 없이 모달 닫기
