### ISSUE TITLE
[FEATURE] 사용자-메뉴 리스트 

### ISSUE THREAD

**Issue by Anyudbwls** [Cafe-Manage-Service-CAFE-IN/cafe-in#19]
## 🌳 작업 브랜치

`feature/#19`

## 📝 TASK 개요
사용자 메뉴 리스트 정보 렌더링 
### 메뉴리스트
- [x] 파이어베이스 DB 연결 확인
- [x] 카테고리별 메뉴 정보 렌더링 
- [x] 메뉴 아이템 클릭시 옵션모달창에 추가한 옵션 메뉴 추가 

### 선택한 메뉴 
- [x] #24
- [x] seletedContainer에서 담은 메뉴들을 DB에 추가
