### ISSUE TITLE
[FEATURE] 관리자 - 대기 관리 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#2]
## 🌳 작업 브랜치

`feature/#2`

## 📝 TASK 개요
대기 관리 페이지 마크업 및 스타일링 작업
(다크 모드랑 대기 중 | 대기 완료 구분은 기능 구현 때 작업)

## ✅ TO DO 및 진행현황

- [x] 컴포넌트 분리
- [x] 마크업
- [x] 스타일링 적용
- [x] 웹 접근성 높이기 (aria 추가)
- [x] 다크 모드 추가
- [x] 모달 컴포넌트 마크업 및 스타일링
