### ISSUE TITLE
[REFACTOR] 관리자 - 대기 관리 리팩토링

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#23]
## 🌳 작업 브랜치

`refactor/#23`

## 🔨 REFACTORING 개요

- 대기 중 | 대기 완료 선택 시 글자 색상 변경 (styled-component에 props를 전달해서 작업했지만 에러가 계속 있어서 일단 보류한 상태임)
- isWaiting이 false일 때 (대기 완료가 선택되었을 때) 새로 고침 시 isWaiting값이 바뀌는 문제 
- 모달창에서 "예"를 선택하여 DB Update가 이루어졌을 때 따로 새로고침을 해주어야 재렌더링 되는 문제. (useEffect를 사용했지만 해결하지 못함.)
- 여러 곳에 쓰이는 type들을 따로 빼기.
- 대기 아이템이 많아질 때 컴포넌트 안에서 스크롤 처리

## ✅ TODO 및 진행현황

- [x] 대기중 | 대기 완료 선택 시 글자 색상 변경
- [x] localStorage를 사용해서 새로 고침을 해도 isWaiting값이 변하지 않게 설정하기
- [x] 모달창을 통해 DB가 Update 됐을 때 자동으로 렌더링 되게 설정하기
- [x] 대기 아이템 많아질 때 스크롤 처리 및 스크롤 숨기기
- [x] type들 따로 빼서 정리하기

### 1. 대기 중 | 대기 완료 선택 시 글자 색상 변경
`isWaiting` 값을 스타일드 컴포넌트에 props로 넘겨주어 `isWaiting` 값에 따라 다른 색상을 적용 시켰다.

<br/>

### 2. localstorage를 사용해서 새로 고침을 해도 isWaiting 값 유지
대기 중 | 대기 완료를 클릭했을 때마다 setLocalstorage를 시켜주었고, 리렌더링 시 로컬 스토리지에 기존 값이 존재하면 그 값을 가져오도록 설정하였다. (우려되는 점 -> 페이지를 나갔다와도 localstorage가 유지된다. 🙄)

<br/>

### 3. 모달창을 통해 DB가 Update 됐을 때 자동 리렌더링 시키기
파이어스토어에서 데이터를 가져오는 코드를 `getDocs`가 아닌 `onSnapShot`으로 바꾸어, 파이어스토어에서 데이터 변경이 일어나면 자동으로 업데이트 시키도록 설정하였다.

<br/>

### 4. 대기 아이템이 많아지면 스크롤 처리 및 숨기기

```css
	overflow-y: scroll;
	overflow-x: hidden;
	-ms-overflow-style: none;
	scrollbar-width: none;

	&::-webkit-scrollbar {
		display: none;
	}
```

<br/>

### 5. type들 따로 빼서 정리하기
여러 컴포넌트에서 사용하는 WaitingDataType을 따로 빼서 사용했다.

<br/>
<br/>
