### ISSUE TITLE
[FEATURE] 사용자 - 대기 신청 기능 구현

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#26]
## 🌳 작업 브랜치

`feature/#26`

## 📝 TASK 개요
- 대기 관리 [대기 가능 | 대기 마감]과 연동
- 대기 신청 정보 입력 값 받기
- 입력 받은 데이터 파이어스토어에 저장
- 유효성 검사

## ✅ TO DO 및 진행현황

- [x] 대기 가능 클릭 시 대기 신청 가능 |  대기 마감 시 대기 신청 불가능
- [x] 대기 가능 상태에 따라 다르게 렌더링 
- [x] 현재 대기 팀 (당일 날짜) 수 렌더링
- [x] 인원수, 이름, 전화 번호 입력 값 받기
- [x] 인원수가 0명일 땐 disable
- [x] 필수 입력값이 빠지거나 유효성 검사 통과 x 시 신청 불가능하고, 해당 입력창으로 focus
- [x] 대기 번호 처리
- [x] date, status 데이터에 넣어주기
- [x] WaitingList 데이터 DB에 저장

### BugFix
- [x] 대기 신청 페이지 렌더링 시 무한 렌더링 버그 수정 
- [x] 메모이제이션과 useEffect 분리로 불필요한 업데이트 방지
