### ISSUE TITLE
[FEATURE] 사용자 - 대기 신청 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#3]
## 🌳 작업 브랜치

`feature/#3`

## 📝 TASK 개요
대기 신청 페이지 마크업 및 스타일링 작업

## ✅ TO DO 및 진행현황

- [x] 대기 신청 페이지 마크업
- [x] 대기 신청 페이지 스타일링
- [x] 탭 접근성 높이기 (aria추가)
- [x] 대기 신청 페이지 다크모드
- [x] 대기 완료 페이지 마크업
- [x] 대기 완료 페이지 스타일링
- [x] 대기 완료 페이지 다크모드
