### ISSUE TITLE
[FEATURE] 관리자 - 카테고리 추가, 수정, 삭제 기능 수정

### ISSUE THREAD

**Issue by somine320** [Cafe-Manage-Service-CAFE-IN/cafe-in#30]
## 🌳 작업 브랜치
feature/#30

## 📝 TASK 개요
- 카테고리 내에 메뉴가 등록되어 있으면 삭제 불가능하게 수정
- 카테고리 이름 수정시 카테고리 안에 포함된 아이템들의 category 값도 수정되도록 변경
- 중복된 카테고리 추가 불가능하게 수정 

## ✅ TO DO 및 진행현황
- [X]  카테고리 추가 기능 수정 
- [X]  카테고리 수정 기능 수정
- [X]  카테고리 삭제 기능 수정
