### ISSUE TITLE
[REFACTOR] 대기 관리 및 대기 신청 페이지 리팩토링

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#37]
## 🌳 작업 브랜치

`refactor/#37`

## 🔨 REFACTORING 개요

- 불필요한 recoil 사용 수정
- 대기 마감 시, 대기가 마감 되었습니다 라는 메세지를 대기 리스트 맨 밑에 띄우기
- 대기 신청 시 유효성 검사 안내 방식 변경 -> 모달창 or 입력창 밑에 메세지 띄우기

## ✅ TODO 및 진행현황

- [x] `isWaiting` 값 다시 useState로 관리하기
- [x] 대기 마감 메세지 대기 리스트에 띄우기
- [x] 대기 신청 시 유효성 검사 안내 방식 변경하기
- [x] 대기 신청 완료 시 뜨는 모달창 변경하기
- [x] 대기 신청 실패 시 모달창 띄우기
- [x] 뒤로가기 버튼 클릭 시 로컬 스토리지의 `isWaiting` 값을 다시 `true`로 바꾸기
- [x] 대기 리스트에서 알림 클릭 시 모달에 대기하는 사용자의 이름을 띄우기
- [x] 대기 완료 페이지 시간 지나면 자동으로 홈으로 이동하기

## 🚧 REFACTOR 리포트

- isWaiting 값은 한 컴포넌트에서만 사용되므로 recoil로 관리하는 건 과하기 때문에 useState로 관리하도록 코드를 수정하였다.
- 대기 마감 시, 대기 진행 명단 리스트를 숨기고 대기 마감 메세지를 띄웠는데 대기 마감을 선택해도 대기 리스트가 존재할 수 있으므로 대기 리스트 맨 밑에다가 대기 마감 메세지를 띄웠다.
- 대기 신청 시 유효성 검사에 통과하지 못하면 alert창을 띄워 안내하였으나 입력창 밑에 메세지를 띄우는 걸로 변경하여 빠르고 직접적으로 확인할 수 있게 변경하였다.
- 대기 신청 시, 대기 신청이 성공했을 때와 실패했을 때를 나눠서 모달창을 띄웠다. 통신 등의 문제로 대기 실패를 할 경우에도 안내가 필요하다고 판단하여 추가하였다.
- 뒤로가기 버튼 클릭 시 localstorage에 있는 isWaiting 값을 다시 true로 바꾸어서 새로 대기 관리 페이지에 들어왔을 때 "대기 중인 명단"이 렌더링되도록 하였다.
- 대기 리스트에서 알림 클릭 시 모달에 대기하는 사용자의 이름을 띄웠다.

<br/>
<br/>
