### ISSUE TITLE
[FEATURE] 사용자 - 메뉴 조회 및 선택 마크업스타일링

### ISSUE THREAD

**Issue by Anyudbwls** [Cafe-Manage-Service-CAFE-IN/cafe-in#4]
## 🌳 작업 브랜치

`feature/#4`

## 📝 TASK 개요
메뉴 조회 및 선택 페이지 마크업 스타일링

## ✅ TO DO 및 진행현황

- [x] 메뉴 조회 마크업
- [x] 메뉴 조회 스타일링
- [x] 옵션 메뉴 선택 모달 마크업 
- [x] 옵션 메뉴 선택 모달 스타일링
