### ISSUE TITLE
[FEATURE] 사용자 - 옵션 & 버튼 

### ISSUE THREAD

**Issue by Anyudbwls** [Cafe-Manage-Service-CAFE-IN/cafe-in#40]
## 🌳 작업 브랜치

`feature/#40`

## 📝 TASK 개요
옵션 추가선택시 가격 + 500원 
selectedItem 1 이상일때 버튼 색상 변경 
메뉴 추가 안할때 아무것도 안누른 상태로 일정이상 지나면 selectedItem 삭제 
## ✅ TO DO 및 진행현황

- [x] 옵션 추가선택 가격 +500원 더하기
- [x] selectedItem 수량 1 이상일때 - 버튼 색상 변경 
- [x] 특정 시간 후 selectedITem 삭제
