### ISSUE TITLE
[FEATURE] 관리자 - 테마 설정 및 색상 설정

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#43]
## 🌳 작업 브랜치

`feature/#43`

## 📝 TASK 개요
- 테마 설정 및 색상 설정 페이지 마크업 및 스타일링
- 테마 설정 기능 구현
- 테마 및 색상 변경에 따른 스타일 적용

## ✅ TO DO 및 진행현황

- [x] 테마 설정 및 색상 설정 페이지 디자인
- [x] 색상 추가하기
- [x] 아이콘 assets 추가
- [x] 마크업
- [x] 스타일링 적용
- [x] 테마 관리 상태 추가하기
- [x] 색상 변경 변수 추가해서 테스트
- [x] 기존 스타일 코드에 색상 변수로 교체하기
- [x] 테마 설정 및 색상 설정 페이지 배경색을 현재 선택 색상으로 변경하기
- [x] 대기 신청 페이지 수량 아이콘 설정 색상으로 변경하기
- [x] 테마 색상 마지막으로 점검 및 색상 수정
