### ISSUE TITLE
[FEATURE] 사용자 - 주문내역확인 페이지 마크업 & 스타일링 

### ISSUE THREAD

**Issue by Anyudbwls** [Cafe-Manage-Service-CAFE-IN/cafe-in#5]
## 🌳 작업 브랜치

`feature/#5`

## 📝 TASK 개요
주문 내역확인 마크업 및 스타일링 

## ✅ TO DO 및 진행현황

- [x] 주문내역 확인 마크업
- [x] 주문내역 확인 스타일링
- [x] 포인트 번호 입력 모달 마크업 스타일링
- [x] 적립확인 안내 모달 마크업 스타일링 
- [x] 포인트 회원 확인 마크업 스타일링
- [x] 포인트 최종 확인 마크업 스타일링
