### ISSUE TITLE
[FEATURE] 사용자 - 포인트 적립 & 포인트 사용 

### ISSUE THREAD

**Issue by Anyudbwls** [Cafe-Manage-Service-CAFE-IN/cafe-in#52]
## 🌳 작업 브랜치

`feature/#52`

## 📝 TASK 개요
핸드폰 번호 입력시 기존의 회원인지 아닌지 판별, 
기본 회원 -> 적립 되었습니다 .
새로운 회원 -> 환영합니다. 
한번 적립시 1,000포인트 적립. 
포인트사용 클릭, 포인트 회원 핸드폰 뒷자리 4자리로 조회 
새로운 회원일시 경고창 보내고 기존 회원이면 포인트 사용 
포인트 사용 입력시 데이터에서 포인트 차감 

## ✅ TO DO 및 진행현황

- [x] 파이어스토어 point 연결 
- [x] 핸드폰 번호 입력시 저장 
- [x] 저장할때 1000포인트 저장 
- [x] 포인트 사용시 핸드폰 뒷자리로 확인 
- [x] 잔여 포인트 보여줌 
- [x] 전액 누를때 가지고 있는 전액 포인트 쓸수있음 
- [x] 확인 누르면 포인트 사용 , 데이터에도 가지고있는 포인터 차감됨
