### ISSUE TITLE
[FEATURE] 관리자 - 메뉴 관리 페이지 기능 수정 

### ISSUE THREAD

**Issue by somine320** [Cafe-Manage-Service-CAFE-IN/cafe-in#55]
## 🌳 작업 브랜치
feature/#55

## 📝 TASK 개요
메뉴 관리 페이지 기능 수정 

## ✅ TO DO 및 진행현황
- [X] form 태그 사용된 부분 submit 기본 동작 막기
- [X] 수정 모달 로그인 여부 확인하는 방법 로컬스토리지로 수정 
- [X] 이미지 등록/수정 label focus 스타일 추가 및 키보드 작동 추가 
- [X] 이미지 태그 alt 속성 체크
- [X] components> adminMode >ManagementHeader 컴포넌트 재사용 
- [X] 헤더 버튼 컴포넌트 분리
