### ISSUE TITLE
[FEATURE] 썸네일 및 나머지 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#57]
## 🌳 작업 브랜치

`feature/#57`

## 📝 TASK 개요
- 썸네일 디자인
- 시작 페이지, 메뉴 페이지 디자인
- 404 페이지 디자인 
- 파비콘 추가 및 타이틀 변경
- 페이지들 마크업 및 스타일링
- 색상 테마 변경

## ✅ TO DO 및 진행현황

- [x] 파비콘 추가 및 타이틀 변경 -> 임의로 설정, 회의 이후 변경
- [x] 썸네일 디자인
- [x] 시작 페이지, 메뉴 페이지 디자인
- [x] 404 페이지 디자인
- [x] 썸네일, 404 페이지 마크업 및 스타일링
- [x] 썸네일 페이지 웹 접근성 높이기
- [x] 시작 페이지 마크업 및 스타일링
- [x] 시작 페이지 웹 접근성
- [x] 관리자 메뉴 페이지 마크업 및 스타일링
- [x] 관리자 메뉴 페이지 웹 접근성
- [x] 색상에 따른 Header, Btn 색상 변경 및 보라색 색상 변경
