### ISSUE TITLE
[FEATURE] 관리자 - 메뉴 관리 / 주문 내역 확인 페이지 테마 적용 반영 스타일 수정

### ISSUE THREAD

**Issue by somine320** [Cafe-Manage-Service-CAFE-IN/cafe-in#59]
## 🌳 작업 브랜치
feature/#59

## 📝 TASK 개요
색상 테마 적용 방법 수정 
관리자 로그인 페이지 ,메뉴 관리 페이지, 주문 내역 확인 페이지 테마 적용했을 때 색상 적용되도록 스타일 수정

## ✅ TO DO 및 진행현황
- [X] theme 타입 재정의
- [X] ThemeProvider 전달 객체 수정 
- [X] 관리자 로그인 페이지 스타일 수정 
- [X] 메뉴 관리 페이지 스타일 수정 
- [X] 주문 내역 확인 페이지 스타일 수정
