### ISSUE TITLE
[REFACTOR] 페이지 색상 적용 코드 수정 및 페이지 연결하기

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#69]
## 🌳 작업 브랜치

`refactor/#69`

## 🔨 REFACTORING 개요

- 시작 페이지, 관리자 메인 페이지, 대기 관리, 대기 신청, 대기 완료, 테마 설정 페이지 색상 적용 코드 수정
- 관리자 로그인 페이지 연결
- 대기 신청 페이지 연결

## ✅ TODO 및 진행현황

- [x] 시작 페이지 수정
- [x] 관리자 메인 페이지 수정
- [x] 대기 관리 페이지 수정
- [x] 테마 설정 페이지 수정
- [x] 대기 신청 페이지 수정
- [x] 대기 완료 페이지 수정
- [x] 관리자 로그인 페이지 연결
- [x] 대기 신청 페이지 연결
- [x] 관리자 로그인 엔터 키 이벤트 적용
