### ISSUE TITLE
[FEATURE] 관리자 - 매출 내역 조회 페이지 마크업 및 스타일링

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#75]
## 🌳 작업 브랜치

`feature/#75`

## 📝 TASK 개요
- 매출 내역 조회 페이지 디자인
- 매출 내역 조회 페이지 마크업 및 스타일링
- 웹 접근성 높이기
- 매출 내역 데이터 렌더링
- 특정 날짜, 특정 달의 데이터 렌더링
- 버튼을 통해 날짜, 달 변경

## ✅ TO DO 및 진행현황

- [x] 매출 내역 조회 페이지 디자인
- [x] 매출 내역 조회 페이지 마크업
- [x] 매출 내역 조회 페이지 스타일링
- [x] 웹 접근성 높이기
- [x] 매출 내역 데이터 렌더링
- [x] 특정 날짜, 특정 달의 데이터 렌더링
- [x] 버튼을 통해 타겟 날짜, 달 변경
