### ISSUE TITLE
[FEATURE] 관리자 - 로그인 리다이렉트 안내 토스트 메세지 

### ISSUE THREAD

**Issue by somine320** [Cafe-Manage-Service-CAFE-IN/cafe-in#80]
## 🌳 작업 브랜치
feature/#80

## 📝 TASK 개요
- 로그인 리다이렉트 안내 토스트 메세지 추가
- 로그인 페이지 디테일 수정 

## ✅ TO DO 및 진행현황
- [X] 로그인 리다이렉트 안내 토스트 메세지 마크업 및 스타일링
- [X] 리다이렉트 안내 토스트 메세지 메인 페이지로 이동하는 기능 구현 
- [X] 로그인 페이지 로고 클릭시 메인 페이지로 이동 
- [X] 로그인 페이지 높이 지정
