### ISSUE TITLE
[FEATURE] 관리자 - 포인트 내역 조회 페이지 수정

### ISSUE THREAD

**Issue by eeeyooon** [Cafe-Manage-Service-CAFE-IN/cafe-in#88]
## 🌳 작업 브랜치

`feature/#88`

## 📝 TASK 개요

관리자 포인트 내역 조회 페이지 수정

## ✅ TO DO 및 진행현황

- [x] Header 공용 컴포넌트로 변경
- [x] 포인트 내역 조회 페이지 스타일링 수정
- [x] 불필요한 임포트 정리 및 색상 적용 코드 수정 
- [x] 현재 페이지 번호 스타일 수정
- [x] 포인트 내역 오래된 순으로 정렬해서 렌더링
