### ISSUE TITLE
[REFACTOR]사용자- 메뉴리스트 , 주문확인 내역, 선택아이템 수정 

### ISSUE THREAD

**Issue by Anyudbwls** [Cafe-Manage-Service-CAFE-IN/cafe-in#91]
## 🌳 작업 브랜치

`feature/#91`

## 🔨 REFACTORING 개요

메뉴 주문 들어갔을때  테이크 아웃 true,false  결정  
세자리수 컴마 함수 사용 
메뉴리스트 들어갔을때 커피 카테고리 선택된 상태로 
메뉴리스트 헤더 디크모드 클릭시 색상 변경 
주문 내역 확인 이미지 각 메뉴 아이템 이미지에 맞게 수정 

 포인트 500이하거나 횐갑 안되어있으면 toast 내보내기  
 포인트  전액 누를때 포인트 사용 안변함 수정 
메뉴아이템 선택하고 아무것도 안누르고 뒤로가기 눌렀을때 OrderCheck 에 남아 있음 
메뉴 클릭안할시 주문확인페이지로 안넘어가야함 

## ✅ TODO 및 진행현황

- [x] 메뉴리스트 (헤더 카테고리 , 다크모드 스타일,메뉴 아이템 다 안보임..  )
- [x] 색상코드 수정 
- [x] 첫 화면 tackeOut 
- [x]  포인트  전액 누를때 UI 수정 
- [x] 메뉴선택 주문하기 버튼 비활성화
- [x] 주문내역 이미지 수정
